# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : "https://cristina-mg.github.io" # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : "/Portfolio-Text" # does not include hostname
title   : CRISTINA MARTINEZ GARCIA
description: > # this means to ignore newlines until "Language & timezone"
  Your Site Description

collections:
  projects:
    output: true
    permalink: /projects/:title/



# Colecciones personalizadas
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Idioma y zona horaria
lang: es
timezone: Europe/Madrid

# Información del autor
author:
  type: person
  name: Cristina Martínez García
  url: https://cristina-mg.github.io
  avatar: /assets/images/avatar.png
  bio: Analista de datos especializada en dashboards e inteligencia de negocio.
  email: cmzgar@gmail.com
  linkedin: cristina-martínez-garcía-data
  github: Cristina-MG

# Enlaces internos
paths:
  root: /
  home: /
  archive: /archive.html
  rss: /feed.xml

# Configuración por defecto para posts y proyectos
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
  - scope:
      path: ""
      type: projects
    values:
      layout: article
      show_excerpt: true
      show_info: true
      readmore: true

# Markdown y resaltado de sintaxis
markdown: kramdown
highlighter: rouge
permalink: date

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Exclusiones (archivos/carpetas que no deben procesarse)
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README-*.md
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor